name: attend_master
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  permission_handler: ^11.4.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  shared_preferences: ^2.5.2
  flutter_background_service: ^5.1.0
  flutter_local_notifications: ^18.0.1
  device_info_plus: ^11.3.0
  dio: ^5.8.0+1
  get: ^4.7.2
  intl: ^0.20.2
#  workmanager: ^0.5.2
  flutter_foreground_task: ^8.17.0
  fluttertoast: ^8.2.12
  google_fonts: ^6.1.0
  table_calendar: ^3.0.9
  fl_chart: ^0.66.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700